[package]
name = "word-count"
version = "0.1.0"
description = "Parses a string to find all unique words and how many times they were used"
authors = ["Andrew Zhang <kanjigawa@gmail.com>"]

[dependencies]
serde_json = "1.0"
pdf-extract = "0.7.5"
lazy_static = "1.4.0"
regex = "1.10.4"
